if(typeof jQuery==="undefined"){throw new Error("AdminBD requires jQuery");}
$.AdminBD={};$.AdminBD.options={navbarMenuSlimscroll:true,navbarMenuSlimscrollWidth:"3px",navbarMenuHeight:"200px",animationSpeed:500,sidebarToggleSelector:"[data-toggle='offcanvas']",sidebarPushMenu:true,sidebarSlimScroll:true,sidebarExpandOnHover:false,enableBoxRefresh:true,enableBSToppltip:true,BSTooltipSelector:"[data-toggle='tooltip']",enableFastclick:false,enableControlSidebar:true,controlSidebarOptions:{toggleBtnSelector:"[data-toggle='control-sidebar']",selector:".control-sidebar",slide:true},enableBoxWidget:true,boxWidgetOptions:{boxWidgetIcons:{collapse:'fa-minus',open:'fa-plus',remove:'fa-times'},boxWidgetSelectors:{remove:'[data-widget="remove"]',collapse:'[data-widget="collapse"]'}},directChat:{enable:true,contactToggleSelector:'[data-widget="chat-pane-toggle"]'},screenSizes:{xs:480,sm:768,md:992,lg:1200}};$(function(){"use strict";$("body").removeClass("hold-transition");if(typeof AdminBDOptions!=="undefined"){$.extend(true,$.AdminBD.options,AdminBDOptions);}
var o=$.AdminBD.options;_init();$.AdminBD.layout.activate();$.AdminBD.tree('.sidebar');if(o.enableControlSidebar){$.AdminBD.controlSidebar.activate();}
if(o.navbarMenuSlimscroll&&typeof $.fn.slimscroll!=='undefined'){$(".navbar .menu").slimscroll({height:o.navbarMenuHeight,alwaysVisible:false,size:o.navbarMenuSlimscrollWidth}).css("width","100%");}
if(o.sidebarPushMenu){$.AdminBD.pushMenu.activate(o.sidebarToggleSelector);}
if(o.enableBSToppltip){$('body').tooltip({selector:o.BSTooltipSelector});}
if(o.enableBoxWidget){$.AdminBD.boxWidget.activate();}
if(o.enableFastclick&&typeof FastClick!=='undefined'){FastClick.attach(document.body);}
if(o.directChat.enable){$(document).on('click',o.directChat.contactToggleSelector,function(){var box=$(this).parents('.direct-chat').first();box.toggleClass('direct-chat-contacts-open');});}
$('.btn-group[data-toggle="btn-toggle"]').each(function(){var group=$(this);$(this).find(".btn").on('click',function(e){group.find(".btn.active").removeClass("active");$(this).addClass("active");e.preventDefault();});});});function _init(){'use strict';$.AdminBD.layout={activate:function(){var _this=this;_this.fix();_this.fixSidebar();$(window,".wrapper").resize(function(){_this.fix();_this.fixSidebar();});},fix:function(){var neg=$('.main-header').outerHeight()+$('.main-footer').outerHeight();var window_height=$(window).height();var sidebar_height=$(".sidebar").height();if($("body").hasClass("fixed")){$(".content-wrapper, .right-side").css('min-height',window_height-$('.main-footer').outerHeight());}else{var postSetWidth;if(window_height>=sidebar_height){$(".content-wrapper, .right-side").css('min-height',window_height-neg);postSetWidth=window_height-neg;}else{$(".content-wrapper, .right-side").css('min-height',sidebar_height);postSetWidth=sidebar_height;}
var controlSidebar=$($.AdminBD.options.controlSidebarOptions.selector);if(typeof controlSidebar!=="undefined"){if(controlSidebar.height()>postSetWidth)
$(".content-wrapper, .right-side").css('min-height',controlSidebar.height());}}},fixSidebar:function(){if(!$("body").hasClass("fixed")){if(typeof $.fn.slimScroll!=='undefined'){$(".sidebar").slimScroll({destroy:true}).height("auto");}
return;}else if(typeof $.fn.slimScroll==='undefined'&&window.console){window.console.error("Error: the fixed layout requires the slimscroll plugin!");}
if($.AdminBD.options.sidebarSlimScroll){if(typeof $.fn.slimScroll!=='undefined'){$(".sidebar").slimScroll({destroy:true}).height("auto");$(".sidebar").slimscroll({height:($(window).height()-$(".main-header").height())+"px",color:"rgba(0,0,0,0.2)",size:"3px"});}}}};$.AdminBD.pushMenu={activate:function(toggleBtn){var screenSizes=$.AdminBD.options.screenSizes;$(document).on('click',toggleBtn,function(e){e.preventDefault();if($(window).width()>(screenSizes.sm-1)){if($("body").hasClass('sidebar-collapse')){$("body").removeClass('sidebar-collapse').trigger('expanded.pushMenu');}else{$("body").addClass('sidebar-collapse').trigger('collapsed.pushMenu');}}
else{if($("body").hasClass('sidebar-open')){$("body").removeClass('sidebar-open').removeClass('sidebar-collapse').trigger('collapsed.pushMenu');}else{$("body").addClass('sidebar-open').trigger('expanded.pushMenu');}}});$(".content-wrapper").click(function(){if($(window).width()<=(screenSizes.sm-1)&&$("body").hasClass("sidebar-open")){$("body").removeClass('sidebar-open');}});if($.AdminBD.options.sidebarExpandOnHover||($('body').hasClass('fixed')&&$('body').hasClass('sidebar-mini'))){this.expandOnHover();}},expandOnHover:function(){var _this=this;var screenWidth=$.AdminBD.options.screenSizes.sm-1;$('.main-sidebar').hover(function(){if($('body').hasClass('sidebar-mini')&&$("body").hasClass('sidebar-collapse')&&$(window).width()>screenWidth){_this.expand();}},function(){if($('body').hasClass('sidebar-mini')&&$('body').hasClass('sidebar-expanded-on-hover')&&$(window).width()>screenWidth){_this.collapse();}});},expand:function(){$("body").removeClass('sidebar-collapse').addClass('sidebar-expanded-on-hover');},collapse:function(){if($('body').hasClass('sidebar-expanded-on-hover')){$('body').removeClass('sidebar-expanded-on-hover').addClass('sidebar-collapse');}}};$.AdminBD.tree=function(menu){var _this=this;var animationSpeed=$.AdminBD.options.animationSpeed;$(document).off('click',menu+' li a').on('click',menu+' li a',function(e){var $this=$(this);var checkElement=$this.next();if((checkElement.is('.treeview-menu'))&&(checkElement.is(':visible'))&&(!$('body').hasClass('sidebar-collapse'))){checkElement.slideUp(animationSpeed,function(){checkElement.removeClass('menu-open');});checkElement.parent("li").removeClass("active");}
else if((checkElement.is('.treeview-menu'))&&(!checkElement.is(':visible'))){var parent=$this.parents('ul').first();var ul=parent.find('ul:visible').slideUp(animationSpeed);ul.removeClass('menu-open');var parent_li=$this.parent("li");checkElement.slideDown(animationSpeed,function(){checkElement.addClass('menu-open');parent.find('li.active').removeClass('active');parent_li.addClass('active');_this.layout.fix();});}
if(checkElement.is('.treeview-menu')){e.preventDefault();}});};$.AdminBD.controlSidebar={activate:function(){var _this=this;var o=$.AdminBD.options.controlSidebarOptions;var sidebar=$(o.selector);var btn=$(o.toggleBtnSelector);btn.on('click',function(e){e.preventDefault();if(!sidebar.hasClass('control-sidebar-open')&&!$('body').hasClass('control-sidebar-open')){_this.open(sidebar,o.slide);}else{_this.close(sidebar,o.slide);}});var bg=$(".control-sidebar-bg");_this._fix(bg);if($('body').hasClass('fixed')){_this._fixForFixed(sidebar);}else{if($('.content-wrapper, .right-side').height()<sidebar.height()){_this._fixForContent(sidebar);}}},open:function(sidebar,slide){if(slide){sidebar.addClass('control-sidebar-open');}else{$('body').addClass('control-sidebar-open');}},close:function(sidebar,slide){if(slide){sidebar.removeClass('control-sidebar-open');}else{$('body').removeClass('control-sidebar-open');}},_fix:function(sidebar){var _this=this;if($("body").hasClass('layout-boxed')){sidebar.css('position','absolute');sidebar.height($(".wrapper").height());if(_this.hasBindedResize){return;}
$(window).resize(function(){_this._fix(sidebar);});_this.hasBindedResize=true;}else{sidebar.css({'position':'fixed','height':'auto'});}},_fixForFixed:function(sidebar){sidebar.css({'position':'fixed','max-height':'100%','overflow':'auto','padding-bottom':'50px'});},_fixForContent:function(sidebar){$(".content-wrapper, .right-side").css('min-height',sidebar.height());}};$.AdminBD.boxWidget={selectors:$.AdminBD.options.boxWidgetOptions.boxWidgetSelectors,icons:$.AdminBD.options.boxWidgetOptions.boxWidgetIcons,animationSpeed:$.AdminBD.options.animationSpeed,activate:function(_box){var _this=this;if(!_box){_box=document;}
$(_box).on('click',_this.selectors.collapse,function(e){e.preventDefault();_this.collapse($(this));});$(_box).on('click',_this.selectors.remove,function(e){e.preventDefault();_this.remove($(this));});},collapse:function(element){var _this=this;var box=element.parents(".box").first();var box_content=box.find("> .box-body, > .box-footer, > form  >.box-body, > form > .box-footer");if(!box.hasClass("collapsed-box")){element.children(":first").removeClass(_this.icons.collapse).addClass(_this.icons.open);box_content.slideUp(_this.animationSpeed,function(){box.addClass("collapsed-box");});}else{element.children(":first").removeClass(_this.icons.open).addClass(_this.icons.collapse);box_content.slideDown(_this.animationSpeed,function(){box.removeClass("collapsed-box");});}},remove:function(element){var box=element.parents(".box").first();box.slideUp(this.animationSpeed);}};}